import { z } from 'zod';

export const requestActionSchema = z.object({
    bookUuid: z.string().uuid().optional(),
    bookTitleId: z.string().max(255).nullable().optional(),
    accessionNumber: z.string().nullable().optional(),
    categoryName: z.string().nullable().optional(),
    classificationNumber: z.string().nullable().optional(),
    author1: z.string().nullable().optional(),
    author2: z.string().nullable().optional(),
    otherAuthors: z.string().nullable().optional(),
    authorType1: z.string().nullable().optional(),
    authorType2: z.string().nullable().optional(),
    otherAuthorsType: z.string().nullable().optional(),
    bookTitle: z.string().nullable().optional(),
    publisher: z.string().nullable().optional(),
    place: z.string().nullable().optional(),
    yearOfPublication: z.string().nullable().optional(),
    romanPages: z.string().nullable().optional(),
    numbericPages: z.string().nullable().optional(),
    isbn: z.string(), // required
    instituteName: z.string().optional(),
    instituteUuid: z.string().uuid().optional(),
    keyWords: z.array(z.string()).optional(),
    titleRemarks: z.array(z.string()).optional(),
    subjectName: z.string().optional(),
    subSubjectName: z.string().optional(),
    language: z.string().optional(),
    bookSeries: z.string().optional(),
    departent: z.string().optional(),
    edition: z.string().optional(),
    titleImages: z.string().nullable().optional(),
    totalCount: z.number().optional(),
    availableCount: z.number().optional(),
    createdAt: z.date().optional(),
    updatedAt: z.date().optional(),
  
    // BookCopy fields
    bookCopyUuid: z.string().uuid().optional(),
    price: z.string().nullable().optional(),
    supplierPrice: z.string().nullable().optional(),
    dateReceipt: z.date().nullable().optional(),
    sourceOfAcquisition: z.string().nullable().optional(),
    billNo: z.string().nullable().optional(),
    billDate: z.date().nullable().optional(),
    keyNo: z.string().nullable().optional(),
    rowNo: z.string().nullable().optional(),
    copyRemarks: z.array(z.string()).optional(),
    isAvailable: z.boolean().optional(),
    isArchived: z.boolean().optional(),
    loaned: z.boolean().optional(),
    loanReturnDate: z.date().optional(),
    donated: z.boolean().optional(),
    bookNumber: z.string().optional(),
    bookSize: z.string().optional(),
    isBound: z.boolean().optional(),
    lockStatus: z.boolean().optional(),
    barcode: z.string().nullable().optional(),
    bindInfo: z.string().nullable().optional(),
    grantName: z.string().optional(),
    bookCondition: z.string().optional(),
    copyImage: z.string().nullable().optional(),
});

export type TRequestActionDTO = z.infer<typeof requestActionSchema>;
